[package]
name = "rustyPC"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "=2.3"
inquire = "0.6.2"
log = "0.4"
env_logger = "0.10"
